var dice=require("./export");
console.log(dice);
var die=dice.game;
die.size=10;
console.log(die.size);
console.log(die.roll());
console.log(die.roll());
console.log(die);
console.log(die.count); 
//console.log(game.size);